### ISSUE TITLE
Cannot install in PI4

### ISSUE THREAD

**Issue by Lorenzi70** [kevinboone/solunar2#2]
Hi, being a user of the older solunar, I tried to install solunar2 on a Raspberry PI4 but when I try to compile (sudo make) I get the following error: 
src/numberformat.c: In function ‘numberformat_space_64’:
src/numberformat.c:195:21: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int64_t’ {aka ‘long long int’} [-Werror=format=]
     sprintf (in, "%ld", n);
                   ~~^   ~
                   %lld

So cannot test the new one. Pity as the Json output would simplify a lot my current parsing.
Regards
Marco

**Comment by kevinboone** [comment]
Hi. Try removing the "-Werror" entry in the Makefile. By default all 
warnings are treated as fatal, and this one shouldn't be. None of the 
numbers used in Solunar are large enough to need a 64-bit integer, but 
I'm using a general-purpose routine that works on numbers that might be 
this large. I'll try to fix this properly when I get chance -- I'm away 
from my computer right now. Sorry about that.

**Comment by Lorenzi70** [comment]
Thanks for the fast reply! Entry removed but get the same error
Regards
Marco

**Comment by kevinboone** [comment]
Hi. You'll still get the error message, but the program should build and 
run if -Werror is removed. If not, please post the complete output when 
running make.

**Comment by Lorenzi70** [comment]
It works. had to change makefile in "/home/pi/solunar2/klib" and not the one in the root. In fact there are three makefile, last one in "libsolunar", which is a bit confusing. 
Thanks, I can test it now
Regards
Marco

**Comment by kevinboone** [comment]
Closing because I removed -Werror.
